/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BlogPost: typeof import('./components/BlogPost.vue')['default']
    CreatePost: typeof import('./components/CreatePost.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PostEditor: typeof import('./components/PostEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
